CREATE DATABASE Relacion_NaN
GO
USE Relacion_NaN
GO

CREATE TABLE Clientes(
	DNI SMALLINT PRIMARY KEY NOT NULL,
	Nombre VARCHAR(30) NOT NULL,
	Apellido VARCHAR(30) NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL 
)
GO

CREATE TABLE Producto(
	ID SMALLINT PRIMARY KEY NOT NULL,
	Descripcion VARCHAR(50) NOT NULL,
	Precio MONEY NOT NULL,
	Stock SMALLINT NOT NULL
)
GO

CREATE TABLE Venta(
	ID INT PRIMARY KEY NOT NULL,
	ClienteID SMALLINT NOT NULL,
	ProductoID SMALLINT NOT NULL,
	Fecha DATE NOT NULL
)