CREATE DATABASE Relacion_1aN
GO
USE Relacion_1aN
GO

CREATE TABLE Venta(
	IDVenta INT PRIMARY KEY IDENTITY(1,1),
	IDCliente INT NOT NULL,
	IDProducto SMALLINT NOT NULL,
	Fecha DATE CHECK(Fecha <= GETDATE())
)
GO

CREATE TABLE Cliente(
	IDCliente INT PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(30) NOT NULL,
	Apellido VARCHAR(30) NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE
)
GO

ALTER TABLE Venta
ADD CONSTRAINT FK_IDCliente FOREIGN KEY (IDCliente)
REFERENCES Cliente(IDCliente)
